<a href="https://colab.research.google.com/github/xxoznge/Bigdata_Analyst_Certificate_Korean/blob/main/PART2_NumPy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# NumPy의 연산
import numpy as np

In [ ]:
# 1. 인덱싱 : 인덱스 번호로

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_1d[0]

1

In [11]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

print(arr_2d[-1, -1])
print(arr_2d[0, -1])

[[1 2 3]
 [4 5 6]]
6
3


In [ ]:
# 2. 슬라이싱 : 음수일 경우도 정방향

In [18]:
arr_1d = np.array([1, 2, 3, 4, 5])

print(arr_1d[0:2])
print(arr_1d[:2])
print(arr_1d[0:])
print(arr_1d[:-1])
print(arr_1d[4:])

[1 2]
[1 2]
[1 2 3 4 5]
[1 2 3 4]
[5]


In [33]:
arr_2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11 ,12]])

print(arr_2d[0:4,0])
print(arr_2d[:,0])
print(arr_2d[:2,:2])
print(arr_2d[:-1,:-2])

[ 1  4  7 10]
[ 1  4  7 10]
[[1 2]
 [4 5]]
[[1]
 [4]
 [7]]


In [ ]:
# 3. 단일 배열 객체 범용 함수
# abs / fabs(절댓값), sqrt(제곱근), square(제곱), exp(지수함수), log, log10, sign

In [35]:
arr = np.array([0, 1, -4, 9, -16, 25])

In [36]:
np.abs(arr)

array([ 0,  1,  4,  9, 16, 25])

In [37]:
np.fabs(arr)

array([ 0.,  1.,  4.,  9., 16., 25.])

In [38]:
np.sqrt(arr)

<ipython-input-38-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([ 0.,  1., nan,  3., nan,  5.])

In [39]:
np.square(arr)

array([  0,   1,  16,  81, 256, 625])

In [40]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 1.83156389e-02, 8.10308393e+03,
       1.12535175e-07, 7.20048993e+10])

In [41]:
np.log(arr)

<ipython-input-41-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)
<ipython-input-41-a67b4ae04e95>:1: RuntimeWarning: invalid value encountered in log
  np.log(arr)


array([      -inf, 0.        ,        nan, 2.19722458,        nan,
       3.21887582])

In [42]:
np.log10(arr)

<ipython-input-42-4473232fb1a0>:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)
<ipython-input-42-4473232fb1a0>:1: RuntimeWarning: invalid value encountered in log10
  np.log10(arr)


array([      -inf, 0.        ,        nan, 0.95424251,        nan,
       1.39794001])

In [43]:
np.sign(arr)

array([ 0,  1, -1,  1, -1,  1])

In [ ]:
# round(소수점 반올림), ceil(올림), floor(내림), trunc(잘라)

In [46]:
arr = np.array([1.15, -2.33, 3.957, -4.095])

In [47]:
np.round(arr)

array([ 1., -2.,  4., -4.])

In [48]:
np.round(arr,1)

array([ 1.2, -2.3,  4. , -4.1])

In [49]:
np.ceil(arr)

array([ 2., -2.,  4., -4.])

In [50]:
np.floor(arr)

array([ 1., -3.,  3., -5.])

In [51]:
np.trunc(arr)

array([ 1., -2.,  3., -4.])

In [52]:
# 4. 서로 다른 배열 객체의 범용 함수
# add, subtract(빼기), multiply(곱), divide(나눔), mod(나머지, %), power(제곱, **)

In [56]:
arr1 = np.arange(5)
arr2 = np.arange(1, 10, step = 2)

In [57]:
np.add(arr1, arr2)

array([ 1,  4,  7, 10, 13])

In [58]:
np.subtract(arr1, arr2)

array([-1, -2, -3, -4, -5])

In [59]:
np.multiply(arr1, arr2)

array([ 0,  3, 10, 21, 36])

In [60]:
np.divide(arr1, arr2)

array([0.        , 0.33333333, 0.4       , 0.42857143, 0.44444444])

In [61]:
np.mod(arr1, arr2)

array([0, 1, 2, 3, 4])

In [62]:
np.power(arr1, arr2)

array([     0,      1,     32,   2187, 262144])