<a href="https://colab.research.google.com/github/xxoznge/Bigdata_Analyst_Certificate_Korean/blob/main/PART2_NumPy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1-3. NumPy의 주요 함수와 메소드
import numpy as np

In [ ]:
# 1. 형상 변환 메소드
# reshape(), ravel() / flatten(), transpose()

In [4]:
arr_1d = np.arange(8)
print(arr_1d)

[0 1 2 3 4 5 6 7]


In [5]:
arr_1d.reshape(2,4) # 행 2, 열 4

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [8]:
arr_1d.reshape(2, -1) # 행 2이고 음수 처리한 열은 알아서 배정

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [9]:
np.arange(8).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
np.arange(12).reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [11]:
np.arange(12).reshape(-1,2,2) # 행, 열은 2로 지정 차원은 알아서

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [20]:
# 평탄화

arr = np.arange(12).reshape(3,2,2)
print(arr)
print(arr.reshape(12))
print(arr.ravel()) # 길이 입력 안해도 됨
print(arr.flatten())
print(arr.transpose())
print(arr.T)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  4  8]
  [ 2  6 10]]

 [[ 1  5  9]
  [ 3  7 11]]]
[[[ 0  4  8]
  [ 2  6 10]]

 [[ 1  5  9]
  [ 3  7 11]]]


In [22]:
# 통계 함수
# mean, var, std, min, max, argmi(최솟값 인덱스), argmax