<a href="https://colab.research.google.com/github/xxoznge/Bigdata_Analyst_Certificate_Korean/blob/main/PART2_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# 1-1. NumPy를 활용한 데이터 다루기

import numpy as np

# ndarray : 하나의 데이터 타입 / 다차원 배열 / np.함수명
# array, arange, ones, zeros, full, identity(n)

# .dtype / .shape (형상 정보) / .size / .ndim (차원)

In [8]:
np.array([1, 2, 3])

array([1, 2, 3])

In [9]:
np.array([[1, 2, 3], [1, 2, 3]])

array([[1, 2, 3],
       [1, 2, 3]])

In [10]:
np.array('xxoznge')

array('xxoznge', dtype='<U7')

In [11]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [12]:
np.arange(1, 6, 0.5) # range는 실수안됨

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((2, 5), dtype = 'int32')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.full(5, 4.)

array([4., 4., 4., 4., 4.])

In [17]:
np.full(5, 4.).dtype # (5, 4).dtype은 int32 -> 5, 4, dtype = 'float').dtype 하면 float64로

dtype('float64')

In [20]:
np.full((2, 5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [21]:
# 대각 성분
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
# 3차원
np.ones((3, 4, 5), dtype='int32')

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int32)

In [27]:
# 정보 확인

arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[1, 2, 3], [4, 5, 6]],
    [[1, 2, 3], [4, 5, 6]]
    ])

print(arr_1d.shape, arr_2d.shape, arr_3d.shape)
print(arr_1d.size, arr_2d.size, arr_3d.size)
print(arr_1d.ndim, arr_2d.ndim, arr_3d.ndim)

(3,) (2, 3) (3, 2, 3)
3 6 18
1 2 3
