<a href="https://colab.research.google.com/github/xxoznge/Bigdata_Analyst_Certificate_Korean/blob/main/PART2_DataTransformation2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# 3-2. 데이터 인코딩 : 문자열을 숫자형으로 변환하는 과정 필요

import pandas as pd
import numpy as np

In [5]:
# 1. 라벨 인코딩 : 단순하게 문자열 값을 숫자형 카테고리 값으로 일대일 변환

from sklearn.preprocessing import LabelEncoder

obj = {'Class' : ['A', 'B', 'A', 'C', 'E', 'D', 'D', 'A', 'F']}
df = pd.DataFrame(obj)

# 인코딩
encoder = LabelEncoder() # 객체 생성
encoder.fit(df.Class)    # 적합
labels = encoder.transform(df.Class)  # 변환

# 인코딩 결과
print(labels)

# 숫자 값 대응되는 원본
print(encoder.classes_)

# 디코딩 (원본으로 되돌아가기))
print(encoder.inverse_transform(labels))

[0 1 0 2 4 3 3 0 5]
['A' 'B' 'C' 'D' 'E' 'F']
['A' 'B' 'A' 'C' 'E' 'D' 'D' 'A' 'F']


In [7]:
# numpy.select(condist, choicelist, ...) / 조건 목록, 선택 목록

conditionlist = [(df['Class'] == 'A'),
                 (df['Class'] == 'B'),
                 (df['Class'] == 'C'),
                 (df['Class'] == 'D'),
                 (df['Class'] == 'E'),
                 (df['Class'] == 'F')]
choicelist = list(range(6))

np.select(conditionlist, choicelist)

array([0, 1, 0, 2, 4, 3, 3, 0, 5])

In [8]:
# 시리즈객체.map(arg, ...)

df['Class'].map(arg = {'A' : 0, 'B' : 1, 'C' : 2, 'D' : 3, 'E' : 4, 'F' : 5})

0    0
1    1
2    0
3    2
4    4
5    3
6    3
7    0
8    5
Name: Class, dtype: int64

In [11]:
# 2. 원-핫 인코딩
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

obj = {'Class' : ['A', 'B', 'A', 'C', 'E', 'D', 'D', 'A', 'F']}
df = pd.DataFrame(obj)

# 인코딩
encoder = LabelEncoder() # 객체 생성
encoder.fit(df.Class)    # 적합
labels = encoder.transform(df['Class']).reshape(-1,1)  # 2차원 변환

# 원-핫 인코딩
oh_encoder = OneHotEncoder(sparse = False)
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

oh_labels

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [13]:
# pandas.get_dummies(data, columns=None, drop_first=False, ...)

obj = {'Class' : ['A', 'B', 'A', 'C', 'E', 'D', 'D', 'A', 'F']}
df = pd.DataFrame(obj)
pd.get_dummies(df)

Class_A  Class_B  Class_C  Class_D  Class_E  Class_F
0     True    False    False    False    False    False
1    False     True    False    False    False    False
2     True    False    False    False    False    False
3    False    False     True    False    False    False
4    False    False    False    False     True    False
5    False    False    False     True    False    False
6    False    False    False     True    False    False
7     True    False    False    False    False    False
8    False    False    False    False    False     True

In [14]:
pd.get_dummies(df, drop_first=True)

Class_B  Class_C  Class_D  Class_E  Class_F
0    False    False    False    False    False
1     True    False    False    False    False
2    False    False    False    False    False
3    False     True    False    False    False
4    False    False    False     True    False
5    False    False     True    False    False
6    False    False     True    False    False
7    False    False    False    False    False
8    False    False    False    False     True

In [15]:
# numpy.where() 이용해 라벨 인코딩과 동일한 결과 만들기

df['Class_B'] = np.where(df['Class'] == 'B', 1, 0)
df['Class_C'] = np.where(df['Class'] == 'C', 1, 0)
df['Class_D'] = np.where(df['Class'] == 'D', 1, 0)
df['Class_E'] = np.where(df['Class'] == 'E', 1, 0)
df['Class_F'] = np.where(df['Class'] == 'F', 1, 0)
df

Class  Class_B  Class_C  Class_D  Class_E  Class_F
0     A        0        0        0        0        0
1     B        1        0        0        0        0
2     A        0        0        0        0        0
3     C        0        1        0        0        0
4     E        0        0        0        1        0
5     D        0        0        1        0        0
6     D        0        0        1        0        0
7     A        0        0        0        0        0
8     F        0        0        0        0        1

In [17]:
obj = {'Class' : ['A', 'B', 'A', 'C', 'E', 'D', 'D', 'A', 'F']}
df = pd.DataFrame(obj)

df.loc[df['Class'] == 'B', 'Class_B'] = 1
df.loc[df['Class'] != 'B', 'Class_B'] = 0

df.loc[df['Class'] == 'C', 'Class_C'] = 1
df.loc[df['Class'] != 'C', 'Class_C'] = 0

df.loc[df['Class'] == 'D', 'Class_D'] = 1
df.loc[df['Class'] != 'D', 'Class_D'] = 0

df.loc[df['Class'] == 'E', 'Class_E'] = 1
df.loc[df['Class'] != 'E', 'Class_E'] = 0

df.loc[df['Class'] == 'F', 'Class_F'] = 1
df.loc[df['Class'] != 'F', 'Class_F'] = 0

df

Class  Class_B  Class_C  Class_D  Class_E  Class_F
0     A      0.0      0.0      0.0      0.0      0.0
1     B      1.0      0.0      0.0      0.0      0.0
2     A      0.0      0.0      0.0      0.0      0.0
3     C      0.0      1.0      0.0      0.0      0.0
4     E      0.0      0.0      0.0      1.0      0.0
5     D      0.0      0.0      1.0      0.0      0.0
6     D      0.0      0.0      1.0      0.0      0.0
7     A      0.0      0.0      0.0      0.0      0.0
8     F      0.0      0.0      0.0      0.0      1.0

In [20]:
# 학생의 id를 담은 컬럼과 시험점수를 담은 컬럼으로 구성된 데이터프레임 생성
# 시험점수가 90 이상이면 수, 80 이상이면 우, 70 이상이면 미, 60점 이상이면 양, 60점 이상이면 가로 구분하는 컬럼 새로 생성
# 그 컬럼에 대하여 라벨 인코딩, 원-핫 인코딩 하기

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import pandas as pd
import numpy as np

obj = {'student_id' : ['s1', 's2', 's3', 's4', 's5', 's6'],
       'score' : [55, 90, 85, 71, 63, 99]}
df = pd.DataFrame(obj)

df['grade'] = pd.cut(df['score'],
                     bins = [0, 60, 70, 80, 90, 100],
                     labels = ['가', '양', '미', '우', '수'])

encoder = LabelEncoder()
encoder.fit(df['grade'])
labels = encoder.transform(df['grade'])

print(labels)
print(encoder.classes_)

labels_2d = labels.reshape(-1,1)

oh_encoder = OneHotEncoder(sparse=False)
oh_encoder.fit(labels_2d)
oh_labels = oh_encoder.transform(labels_2d)
print(oh_labels)

[0 4 4 1 3 2]
['가' '미' '수' '양' '우']
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
